# Generated by Django 5.0.7 on 2024-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_loss_percent', models.FloatField()),
                ('leverage', models.FloatField()),
                ('amount_usd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('api_key', models.CharField(max_length=30)),
                ('api_secret', models.CharField(max_length=45)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
