# Generated by Django 5.0.7 on 2024-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('chat_id', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
