# Generated by Django 5.0.7 on 2024-07-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0003_entryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stop_loss_step',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
