# Generated by Django 5.0.7 on 2024-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0005_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
