# Generated by Django 5.0.7 on 2024-07-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0006_settings_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryprice',
            old_name='price',
            new_name='entry_price',
        ),
        migrations.AddField(
            model_name='entryprice',
            name='first_target_price',
            field=models.FloatField(default=0),
        ),
    ]
