# Generated by Django 5.0.7 on 2024-07-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0007_rename_price_entryprice_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryprice',
            name='side',
            field=models.CharField(default='side', max_length=4),
            preserve_default=False,
        ),
    ]
